Create Tensors

In [ ]:
import torch

a = torch.zeros(3,3)
b = torch.zeros(3,3)
c = torch.zeros(3,3)

print(a,b,c)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
x = torch.arange(12)
y = x.reshape(3,4)
z = y.view(2,6)

print(x)
print(y)
print(z)


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [ ]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([2.0, 3.0, 4.0])
c = torch.tensor([5.0, 6.0, 7.0])

print(a+b)
print(torch.dot(a,b))
print(torch.sum(a))
print(torch.mean(a))


tensor([3., 5., 7.])
tensor(20.)
tensor(6.)
tensor(2.)


In [ ]:
import torch as t
x = t.rand(4,4)
print(x)
print(x[0])
print(x[:2]) #take everything up to second row
print(x[:,1]) #take all rows, only take second column

tensor([[0.9265, 0.4204, 0.4103, 0.2111],
        [0.4453, 0.1168, 0.8910, 0.2189],
        [0.6192, 0.0324, 0.8408, 0.3922],
        [0.7045, 0.6880, 0.5192, 0.6560]])
tensor([0.9265, 0.4204, 0.4103, 0.2111])
tensor([[0.9265, 0.4204, 0.4103, 0.2111],
        [0.4453, 0.1168, 0.8910, 0.2189]])
tensor([0.4204, 0.1168, 0.0324, 0.6880])


In [ ]:
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2 + 2 * x + 1
y.backward()
print(x.grad)

tensor(8.)


In [ ]:
import torch.nn as nn
softmax = nn.Softmax(dim=0)
logits = torch.tensor([1.0, 2.0, 3.0])
probs = softmax(logits) #softmax change it to probabilities
print(probs)
print(probs.sum())


tensor([0.0900, 0.2447, 0.6652])
tensor(1.)


In [ ]:
class simpleclassifier(nn.Module):
  def __init__(self):
    super().__init__() #calls the class
    self.linear = nn.Linear(4,3) #nn.linear(in_features, out_features)
    self.softmax = nn.Softmax(dim=1)

  def forward(self, x):
    logits = self.linear(x)
    return self.softmax(logits)

model = simpleclassifier()
x = torch.rand(5,4)
output = model(x)

print(output)
print(output.sum(dim=1))




tensor([[0.2538, 0.4807, 0.2654],
        [0.3560, 0.4435, 0.2005],
        [0.2951, 0.4425, 0.2624],
        [0.2887, 0.4372, 0.2741],
        [0.3591, 0.4421, 0.1987]], grad_fn=<SoftmaxBackward0>)
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000], grad_fn=<SumBackward1>)


In [ ]:
model = nn.Sequential(nn.Linear(6,10), nn.ReLU(), nn.Linear(10,4), nn.Softmax(dim=1))
x = torch.rand(8,6)
output = model(x)
print(output)
print(output.sum(dim=1))

tensor([[0.3231, 0.1980, 0.2353, 0.2435],
        [0.3050, 0.2078, 0.2259, 0.2613],
        [0.3163, 0.1710, 0.2627, 0.2499],
        [0.3046, 0.1930, 0.2379, 0.2645],
        [0.3115, 0.2067, 0.2259, 0.2558],
        [0.3151, 0.1685, 0.2675, 0.2489],
        [0.3077, 0.1757, 0.2600, 0.2566],
        [0.3208, 0.1797, 0.2546, 0.2450]], grad_fn=<SoftmaxBackward0>)
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
       grad_fn=<SumBackward1>)


In [ ]:
import torch
import torch.nn as nn

layer = nn.Linear(3,2)
x = torch.tensor([[1.0, 2.0, 3.0]])
out = layer(x) #calls forward(x), forward pass

manual = x @ layer.weight.T + layer.bias #layer transpose to 2x3 so you can matrix multiply 1x3

print("Layer output: ", out)
print("Manual output:", manual)

Layer output:  tensor([[1.3704, 3.4072]], grad_fn=<AddmmBackward0>)
Manual output: tensor([[1.3704, 3.4072]], grad_fn=<AddBackward0>)


In [ ]:
layer_with_bias = nn.Linear(4,2, bias=True)
layer_without_bias = nn.Linear(4,2, bias=False)
print ("with bias ", list(layer_with_bias.parameters()))
print("without bias", list(layer_without_bias.parameters()))


with bias  [Parameter containing:
tensor([[-0.1620, -0.1374,  0.1819, -0.4813],
        [ 0.4478, -0.2358,  0.2332,  0.0917]], requires_grad=True), Parameter containing:
tensor([-0.1896, -0.1520], requires_grad=True)]
without bias [Parameter containing:
tensor([[ 0.3979,  0.4068, -0.4994, -0.2152],
        [ 0.0641,  0.0121, -0.0634, -0.2482]], requires_grad=True)]


In [ ]:
layer = nn.Linear(3,2, bias=False)
with torch.no_grad():
  layer.weight = nn.Parameter(torch.tensor([
      [1.0,2.0,3.0],
      [0.0,1.0,0.0]
      ]))
  x = torch.tensor([[5.0,6.0,7.0]])
  print(layer(x))

tensor([[38.,  6.]])


In [2]:
import torch

x = torch.rand((2,3))
print(x)
torch.einsum("ij->ji",x)

tensor([[0.4147, 0.7432, 0.6171],
        [0.8232, 0.4039, 0.0862]])


tensor([[0.4147, 0.8232],
        [0.7432, 0.4039],
        [0.6171, 0.0862]])

In [3]:
torch.einsum("ji ->",x) #summation

tensor(3.0883)

In [4]:
torch.einsum("ij -> i", x) #sum rows



tensor([1.7750, 1.3133])

In [7]:
torch.einsum("ij -> j", x) #sum columns

tensor([1.2379, 1.1471, 0.7034])

In [10]:
v = torch.rand((1,3))
torch.einsum("ij,kj -> ik", x, v) #2x1
torch.einsum("ij,kj -> ik", x, x) #2x3, 3x2 , 2x2
torch.einsum("ij, ij -> ij", x, x)

tensor([[0.1720, 0.5524, 0.3809],
        [0.6776, 0.1631, 0.0074]])